---

- name: Install java libraries
  yum: 
    name: java-1.8.0-openjdk.x86_64 
    state: present
    use_backend: yum

- name: Create Opscenter repositories
  copy: 
    dest: /etc/yum.repos.d/opscenter.repo
    content: |
      [opscenter]
      name=DataStax Repository
      baseurl = https://rpm.datastax.com/enterprise
      gpgcheck=0
      enable=1
      gpgkey=https://rpm.datastax.com/rpm/repo_key 

- name: Install opscenter
  yum: name=opscenter state=present

- name: Enable  opscenter  service
  ansible.builtin.systemd:
    name: opscenterd
    enabled: yes

- name: Start  opscenter 
  ansible.builtin.systemd:
    name: opscenterd
    enabled: yes
    state: started