---
# - name: Upgrade all packages
#   ansible.builtin.yum:
#     name: '*'
#     state: latest
- name: Install required libraries
  yum: name={{ packages_list }} state=present

- name: Create cassandra repositories
  copy: 
    dest: /etc/yum.repos.d/cassandra.repo
    content: |
      [cassandra]
      name=Apache Cassandra
      baseurl=https://www.apache.org/dist/cassandra/redhat/311x/
      gpgcheck=1
      repo_gpgcheck=1 
      gpgkey=https://www.apache.org/dist/cassandra/KEYS

- name: Install cassandra
  yum: name=cassandra state=present

- name: Start start cassandra 
  service:
    name: cassandra
    state: started
  
- name: Auto start cassandra 
  service:
    name: cassandra
    enabled: yes
    state: started