---

- hosts: [ "node1", "node2", "node3"]
  user: vagrant
  become: yes
  vars_files:  ../defaults/main.yml
  tasks:

  # - include: dependencies.yml
  # - include: tasks/repositories.yml
  # - include: tasks/java-install.yml
  # - include: tasks/dse-install.yml
  # - include: tasks/start-dse.yml
  - include: CassandraCluster.yml
